# Generated by the Mandarine CLI release pipeline. Do not edit by hand.
class Mandarine < Formula
  desc "Mandarine from the command line: cards and decisions for your agents"
  homepage "https://mandarine.tech"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/alva-do/mandarine-cli/releases/download/0.1.0/mandarine_darwin_arm64.tar.gz"
      sha256 "68d24897b3a26760dc89e721f0b3386542a765c6db51b1195bfd47a1711b8b60"
    end
    on_intel do
      url "https://github.com/alva-do/mandarine-cli/releases/download/0.1.0/mandarine_darwin_amd64.tar.gz"
      sha256 "66ebdb3603c9064d9a65c5d56965179f48222fbee422b1073ef1df6593cc6255"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alva-do/mandarine-cli/releases/download/0.1.0/mandarine_linux_arm64.tar.gz"
      sha256 "4b4dbb7faeb8a7cc1535088641cee1f9cefc9988860fb6aba9b9862a9d42b51e"
    end
    on_intel do
      url "https://github.com/alva-do/mandarine-cli/releases/download/0.1.0/mandarine_linux_amd64.tar.gz"
      sha256 "8119a27af66dd2ced48acf28deea54b09303e2161e04d3ed48c99be81513ce27"
    end
  end

  def install
    bin.install "mandarine"
  end

  test do
    assert_match "mandarine #{version} ", shell_output("#{bin}/mandarine --version")
  end
end
